POST http://localhost:8000/movies
Content-Type: application/json

{
    "title": "AVATAR",
    "description": "avatar the new movie",
    "stock": 60,
    "rentalPrice": 5,
    "salePrice": 35,
    "available": true
}


### patch a movie 

PATCH http://localhost:8000/movies/4
Content-Type: application/json

{
    "description": "new movie"
}

### patch a movie which is available

PATCH http://localhost:8000/movies/1
Content-Type: application/json

{
    "description": "new movie"
}

### put a movie which is available

PUT http://localhost:8000/movies/2
Content-Type: application/json

{
    "title": "LALALALALA",
    "description": "blavblablaSKN",
    "stock": 50,
    "rentalPrice": 9,
    "salePrice": 35
}

### remove a movie with id

DELETE http://localhost:8000/movies/4
Content-Type: application/json

### find by sendiing Req object

GET  http://localhost:8000/movies?sort=description,asc&unavailable=false&size=3&page=1
Content-Type: application/json

### find available movies (only send unavailable variable)

GET http://localhost:8000/movies/true
Content-Type: application/json

### /sales POST

POST http://localhost:8000/sales
Content-Type: application/json

{
    "movieId": 2,
    "customerEmail": "juan3@gmail.com"
}


### /rentals POST

POST http://localhost:8000/rentals
Content-Type: application/json

{
    "movieId": 6,
    "customerEmail": "carlos@sendmail.com"
}

### GET BY TITLE 

GET http://localhost:8000/movies/title/laudo
Content-Type: application/json

### post likes /likes

POST http://localhost:8000/likes
Content-Type: application/json

{
  "movieId": 3,
  "customerEmail":"carlos@park.com"
}    

### GET transsactions

GET http://localhost:8000/transactions/movies/3?from=2021-01-01&to=2021-12-31
Content-Type: application/json
